### ISSUE TITLE
fc_delay suggestion for exception

### ISSUE THREAD

**Issue by jinparksj** [altelch/iso-tp#12]
Hello,

I would like to ask whether it corrects to use the fc_delay function, changing like below, for exceptional case about minimum separation time.

Original Script
void IsoTp::fc_delay(uint8_t sep_time)
{
  if(sep_time < 0x80)
    delay(sep_time);
  else
    delayMicroseconds((sep_time-0xF0)*100);
}

Change version
void IsoTp::fc_delay(uint8_t sep_time)
{
    /*
     * 0x00 - 0x7F: 0 - 127ms
     * 0x80 - 0xF0: reserved
     * 0xF1 - 0xF9: 100us - 900us
     * 0xFA - 0xFF: reserved
     * default 0x7F, 127ms
     */
  if(sep_time <= 0x7F)
    delay(sep_time);
  else if ((sep_time >= 0xF1) && (sep_time <= 0xF9)) 
    delayMicroseconds((sep_time-0xF0)*100);
  else
    delay(0x7F);
}

**Comment by altelch** [comment]
Merged your change.
