### ISSUE TITLE
HVAC seq_id wrong order

### ISSUE THREAD

**Issue by gorghino** [altelch/iso-tp#17]
Hi!
I'm trying to get a 54B message from the HVAC from a Nissan Leaf 2018.
Most of the time I send the message, the lib timeouts because it reads seq_ids in wrong order (or the OBD sends them in a wrong order).

I don't get why I can successfully get a 331B msg without any error from another ECU but the HVAC seems to be problematic.

```
ISO-TP State: 1
Length      : 2
Send SF
Send CAN RAW Data:
Buffer: 744 [8] 02 21 10 00 00 00 00 00 
Start receive...
Received CAN RAW Data:
Buffer: 764 [8] 10 36 61 10 33 3C 36 00 
rxId OK!
FF
First frame received with message length: 48
Send flow controll.
ISO-TP state: 6
Send CAN RAW Data:
Buffer: 744 [8] 30 00 00 00 00 00 00 00 
Received CAN RAW Data:
Buffer: 764 [8] 21 33 3C 00 34 00 00 00 
rxId OK!
CF
ISO-TP state: 6
CF received with message rest length: 48
CF received with seq. ID: 1
Received CAN RAW Data:
Buffer: 764 [8] 22 84 9D 00 00 00 00 00 
rxId OK!
CF
ISO-TP state: 6
CF received with message rest length: 41
CF received with seq. ID: 2
Received CAN RAW Data:
Buffer: 764 [8] 23 00 00 00 00 00 00 00 
rxId OK!
CF
ISO-TP state: 6
CF received with message rest length: 34
CF received with seq. ID: 3
Received CAN RAW Data:
Buffer: 764 [8] 24 32 93 00 00 00 06 00 
rxId OK!
CF
ISO-TP state: 6
CF received with message rest length: 27
CF received with seq. ID: 4
Received CAN RAW Data:
Buffer: 764 [8] 26 00 00 00 00 2C 2C 2C 
rxId OK!
CF
ISO-TP state: 6
CF received with message rest length: 20
Got sequence ID: 6 Expected: 5
Received CAN RAW Data:
Buffer: 764 [8] 27 29 00 28 00 00 00 FF 
rxId OK!
CF
ISO-TP state: 0
CF received with message rest length: 20
Received CAN RAW Data:
Buffer: 764 [8] 25 60 A0 08 90 00 00 00 
rxId OK!
CF
ISO-TP state: 0
CF received with message rest length: 20
ISO-TP Session timeout wait_session=33190 delta=500
```

In the file attached I pasted the LBC 331B msg (First request), multiple bad requests to HVAC until it eventually got one good answer and the Buffer is correctly filled.

Extra question:
I'm interested in first two bytes from 0x22 frame. Is there a way to get that frame only by any chance? Maybe setting the FC somehow for this particular case. 
Is there also a way to 'clean' the flow control in order to restart the request? Sometimes I get some dirty frames from previous requests when I try to stop some and retry.

[hvac-errors.log](https://github.com/altelch/iso-tp/files/7871289/hvac-errors.log)

**Comment by altelch** [comment]
Hi,

I have to admit that I'm totally out of this topic. I wrote this stuff years ago when I had a Dacia Logan MCV. Since then I didn't use this code again. Don't even have the testing equippment at hand :-(  So I think I can't help you any further.

Sorry.
