### ISSUE TITLE
TxMsg does not name a type on example

### ISSUE THREAD

**Issue by alexanderturner** [altelch/iso-tp#3]
Hey there,

Getting the following issue when trying to run the example code running the MCP library from it's master repo.

```
send_receive:17:1: error: 'TxMsg' does not name a type
 TxMsg.Buffer=(uint8_t *)calloc(MAX_MSGBUF,sizeof(uint8_t));
 ^
send_receive:18:1: error: 'RxMsg' does not name a type
 RxMsg.Buffer=(uint8_t *)calloc(MAX_MSGBUF,sizeof(uint8_t));
 ^
exit status 1
'TxMsg' does not name a type
```
Ideas?

**Comment by alexanderturner** [comment]
App compiles if I comment out:
```
//TxMsg.Buffer=(uint8_t *)calloc(MAX_MSGBUF,sizeof(uint8_t));
//RxMsg.Buffer=(uint8_t *)calloc(MAX_MSGBUF,sizeof(uint8_t));
```

**Comment by hardweb-it** [comment]
> Hey there,
> 
> Getting the following issue when trying to run the example code running the MCP library from it's master repo.
> 
> ```
> send_receive:17:1: error: 'TxMsg' does not name a type
>  TxMsg.Buffer=(uint8_t *)calloc(MAX_MSGBUF,sizeof(uint8_t));
>  ^
> send_receive:18:1: error: 'RxMsg' does not name a type
>  RxMsg.Buffer=(uint8_t *)calloc(MAX_MSGBUF,sizeof(uint8_t));
>  ^
> exit status 1
> 'TxMsg' does not name a type
> ```
> 
> Ideas?

Same issue for me, i'm trying investigate on it, but I don't know how is Struct working.
