### ISSUE TITLE
Can not receive CAN message Package over 255 bytes 

### ISSUE THREAD

**Issue by hoangkhai6893** [altelch/iso-tp#4]
I was trying receive 1 CAN message package with 256 bytes, but it not worked. 
After I debugging Source Code , I realized it has 1 issue .  
At the  `uint8_t IsoTp::rcv_ff(struct Message_t* msg)  function : `
```

   msg->len = (rxBuffer[0] & 0x0F) << 8;
  msg->len += rxBuffer[1];
```
 the value of  `msg->len ` can't over 256.
So if we want to receive a package over 256 bytes, it will not work.
This is my solution for that :  
 ```
 over256size = rxBuffer[0] & 0x0F;
  if(over256size != 0)
  {
	  msg->len = over256size  << 8;
	  msg->len += rxBuffer[1];
  else
  {
	  msg->len = rxBuffer[1];
  }

```
Please check it and update your library.
Thank you so much.

**Comment by altelch** [comment]
ISO-TP can have up to 4096 Bytes message length. First Frame of multi frame message contains the lenght in Byte 0 (low nibble) and Byte on -> 12 Bit length. Used only uint8_t which is too short -> changed to unit16_t in iso-tp.h. After this change original code should work. Please give it a try as I don't have any CAN-Setup available to test.

**Comment by hoangkhai6893** [comment]
Understood, thank you for your feedback !
