### ISSUE TITLE
Messages with blocksize > 16

### ISSUE THREAD

**Issue by gurgelmb** [altelch/iso-tp#6]
when try to transmit messages with blocksize higher then 16 it failes, because it waits for fc frame which will never come.
Change line 378 in iso-tp.cpp to:

if (msg->blocksize < 16)
  msg->seq_id %= 16;
else
  msg->seq_id %= msg->blocksize;

**Comment by brandonros** [comment]
lol this needs to be PR'd to master. it's a deadlock otherwise
